<?php

return [
    'en' => [
        'skipper',
        'skippers',
        'hostess',
        'team',
        'chef',
        'management',
        'yacht',
        'yachts',
        'charter',
        'charters',
        'tender',
        'jet ski',
        'fly',
        'flybridge',
        'hard top',
        'open',
        'speed',
        'endurance',
        'first',
        'sun',
        'odyssey',
        'beneteau',
        'jeanneau',
        'azimut',
        'experience',
        'experiences',
        'tour',
        'tours',
        'trip',
        'trips',
        'snorkeling',
        'snorkel',
        'diving',
        'trekking',
        'jogging',
        'weekend',
        'weekends',
        'full day',
        'half day',
        'check-in',
        'check-out',
        'briefing',
        'booking',
        'last minute',
        'design',
        'comfort',
        'luxury',
        'relax',
        'trend',
        'location',
        'top',
        'best',
        'must-see',
        'eco-friendly',
        'pet-friendly',
        'gold',
        'premium',
        'smart',
        'all inclusive',
        'reef',
        'refitting',
        'review',
        'sunset',
        'blue',
        'drink',
        'drinks',
        'snack',
        'snacks',
        'cocktail',
        'home theater',
        'drone',
        'gopro',
        'kasko',
        'wireless',
        'wi-fi'
    ],
    'fr' => [
        'gourmet',
        'bohemien',
        'toilette',
        'toilettes',
        'champagne',
        'dom pérignon',
        'mousse',
        'chic',
        'charme'
    ],
];